name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: .gradle/caches
          key: dependencyinjector-gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependencyinjector
          path: /build/libs/*

      - name: Publish package
        run: ./gradlew publish
        env:
          ARTIFACTORY_USER: BlackEagleEF
          ARTIFACTORY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
